### ISSUE TITLE
Get Random AI orientation and fire location

### ISSUE THREAD

**Issue by vaughnju** [cs361w2019-osu/sprint1-group-2#1]

**Comment by vaughnju** [comment]
I put the code in for Game.js to get a random row, column, and whether or not it is vertical.

**Comment by kindlehl** [comment]
@vaughnju each issue is supposed to represent a user story being solved. This is because the idea behind issues is that there is some feature that is lacking, and someone would fix the issue by submitting a pull request with code that fixes the issue and only the issue. 

Looking at your user stories, it also seems that there is a 'computer' that plays? I thought this would be between two human players, but I may be mistaken.
